//
//  TherapyMetricsTests.swift
//  xdrip
//
//  Created by Paul Plant on 12/8/26.
//  Copyright © 2026 Johan Degraeve. All rights reserved.
//

import XCTest
import SwiftUI
@testable import xdrip

final class TherapyMetricsTests: XCTestCase {
    func testLiveActivityMetricsPreferenceIsIndependentOfChartPreference() {
        let suite = "LiveActivityMetricsTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suite)!
        defer { defaults.removePersistentDomain(forName: suite) }
        XCTAssertTrue(defaults.liveActivityShowIOBCOB)
        defaults.showIOBCOB = false
        XCTAssertTrue(defaults.liveActivityShowIOBCOB)
        defaults.liveActivityShowIOBCOB = false
        defaults.showIOBCOB = true
        XCTAssertFalse(defaults.liveActivityShowIOBCOB)
    }

    func testLiveActivityMetricsVisibilityPreservesStatusAndOldPayloads() throws {
        let status = AIDStatus(condition: .active, style: .loop, statusUpdatedAt: .now,
            lastActivityAt: .now, iob: 1.8, cob: 18, statusTitle: "Looping", staleStatusTitle: "No data")
        var state = XDripWidgetAttributes.ContentState(bgReadingValues: [120], bgReadingDates: [.now],
            isMgDl: true, slopeOrdinal: 4, deltaValueInUserUnit: 0,
            urgentLowLimitInMgDl: 55, lowLimitInMgDl: 70, highLimitInMgDl: 180,
            urgentHighLimitInMgDl: 250, liveActivityType: .large, aidStatus: status)
        XCTAssertTrue(state.showsTherapyMetrics)
        state.showIOBCOB = false
        XCTAssertFalse(state.showsTherapyMetrics)
        XCTAssertNotNil(state.deviceStatusIconImage())
        let encoded = try JSONEncoder().encode(state)
        XCTAssertFalse(try JSONDecoder().decode(XDripWidgetAttributes.ContentState.self, from: encoded).showsTherapyMetrics)
        var legacy = try XCTUnwrap(JSONSerialization.jsonObject(with: encoded) as? [String: Any])
        legacy.removeValue(forKey: "showIOBCOB")
        let decoded = try JSONDecoder().decode(XDripWidgetAttributes.ContentState.self,
            from: JSONSerialization.data(withJSONObject: legacy))
        XCTAssertTrue(decoded.showsTherapyMetrics)
    }

    private let now = Date(timeIntervalSince1970: 1_800_000_000)
    private var settings: TherapyModelSettings {
        TherapyModelSettings()
    }
    private func policy(therapy: TherapyDataSourceType = .none, follow: NightscoutFollowType = .none) -> DataFlowPolicy {
        DataFlowPolicy(isMaster: therapy != .careLink, followerDataSource: .careLink,
            therapyDataSourceSelection: therapy, nightscoutEnabled: therapy == .nightscout,
            masterUploadsGlucoseToNightscout: false, followerUploadsGlucoseToNightscout: false,
            nightscoutFollowType: follow)
    }
    private func entry(_ amount: Double, minutesAgo: Double = 0, isIOB: Bool = true) -> TherapyTreatment {
        TherapyTreatment(date: now.addingTimeInterval(-minutesAgo * 60), amount: amount, isIOB: isIOB)
    }
    private func metric(_ entries: [TherapyTreatment]?, isIOB: Bool = true, at date: Date? = nil) -> TherapyMetricState {
        TherapyMetricsManager.localMetric(entries: entries, isIOB: isIOB, date: date ?? now, settings: settings)
    }

    // Values generated by executing the pinned oref0 JS with JavaScriptCore, not the Swift port.
    func testOpenAPSReferenceParity() {
        let reference: [(Double, Double)] = [(0, 1), (15, 0.9788245454057859), (30, 0.9249701856314995),
            (60, 0.7640057035577161), (75, 0.6726398904581075), (120, 0.41057994214803406),
            (180, 0.15879641537283806), (240, 0.032924868796628814), (299, 0.00000741451802288573), (300, 0)]
        for (minutes, expected) in reference {
            XCTAssertEqual(TherapyCalculations.insulinRemaining(units: 1, minutes: minutes, duration: 300, peak: 75), expected, accuracy: 1e-12)
        }
    }

    func testInsulinBoundariesAndContinuousTime() {
        XCTAssertEqual(TherapyCalculations.insulinRemaining(units: 3, minutes: -1, duration: 300, peak: 75), 0)
        XCTAssertEqual(TherapyCalculations.insulinRemaining(units: 3, minutes: 0, duration: 300, peak: 75), 3)
        XCTAssertEqual(TherapyCalculations.insulinRemaining(units: 3, minutes: 301, duration: 300, peak: 75), 0)
        XCTAssertNotEqual(TherapyCalculations.insulinRemaining(units: 3, minutes: 60.1, duration: 300, peak: 75),
                          TherapyCalculations.insulinRemaining(units: 3, minutes: 60.2, duration: 300, peak: 75))
    }

    func testEveryAllowedInsulinCombinationIsBoundedAndMonotonic() {
        for duration in stride(from: 180.0, through: 600, by: 30) {
            for peak in stride(from: 35.0, through: 120, by: 5) where peak * 2 < duration {
                var previous = 1.0
                for minute in stride(from: 0.0, through: duration, by: 0.5) {
                    let remaining = TherapyCalculations.insulinRemaining(units: 1, minutes: minute, duration: duration, peak: peak)
                    XCTAssertTrue(remaining.isFinite)
                    XCTAssertGreaterThanOrEqual(remaining, 0)
                    XCTAssertLessThanOrEqual(remaining, previous + 1e-12)
                    previous = remaining
                }
                XCTAssertEqual(previous, 0)
            }
        }
    }

    func testLoopKitAbsorptionBoundaries() {
        // Pinned PiecewiseLinearAbsorption: rise=.15, fall=.5, scale=2/1.35.
        let reference: [(Double, Double)] = [(-1, 0), (0, 60), (10, 60),
            (37, 53.333333333333336), (100, 22.22222222222222), (190, 0), (250, 0)]
        for (minute, grams) in reference {
            XCTAssertEqual(TherapyCalculations.carbsRemaining(grams: 60, minutes: minute, duration: 180), grams, accuracy: 1e-10)
        }
    }

    func testCarbDurationsAreMonotonicAndScaleWithMealSize() {
        for duration in stride(from: 60.0, through: 480, by: 30) {
            var previous = 10.0
            for minute in stride(from: 0.0, through: duration + 10, by: 1) {
                let remaining = TherapyCalculations.carbsRemaining(grams: 10, minutes: minute, duration: duration)
                XCTAssertLessThanOrEqual(remaining, previous + 1e-12)
                XCTAssertGreaterThanOrEqual(remaining, 0)
                XCTAssertEqual(TherapyCalculations.carbsRemaining(grams: 20, minutes: minute, duration: duration), remaining * 2, accuracy: 1e-12)
                previous = remaining
            }
            XCTAssertEqual(previous, 0)
        }
    }

    func testDefaultInsulinRemainsActiveBeyondFiveHoursAndEndsAtTen() throws {
        XCTAssertTrue(settings.validInsulin)
        for preset in TherapyInsulinPreset.allCases {
            var model = settings
            model.insulinPeak = preset.peak
            let tail = TherapyMetricsManager.localMetric(entries: [entry(2, minutesAgo: 301)],
                isIOB: true, date: now, settings: model)
            XCTAssertGreaterThan(try XCTUnwrap(tail.value(at: now)), 0)
            for elapsed in [600.0, 601.0] {
                let finished = TherapyMetricsManager.localMetric(entries: [entry(2, minutesAgo: elapsed)],
                    isIOB: true, date: now, settings: model)
                XCTAssertEqual(finished.value(at: now), 0)
                XCTAssertTrue(finished.isVisible(at: now))
            }
        }
    }

    func testOverlappingTreatmentsAreSummedWithoutAmountTimeDeduplication() throws {
        let treatments = [entry(2), entry(2), entry(30, isIOB: false), entry(20, isIOB: false)]
        XCTAssertEqual(try XCTUnwrap(metric(treatments).value(at: now)), 4)
        XCTAssertEqual(try XCTUnwrap(metric(treatments, isIOB: false).value(at: now)), 50)
    }

    func testVisibilityIsSharedAndExpiresAtExactly24Hours() throws {
        let treatments = [entry(2, minutesAgo: 1439)]
        XCTAssertEqual(try XCTUnwrap(metric(treatments).value(at: now)), 0)
        XCTAssertEqual(try XCTUnwrap(metric(treatments, isIOB: false).value(at: now)), 0)
        XCTAssertTrue(metric(treatments).isVisible(at: now.addingTimeInterval(59)))
        XCTAssertFalse(metric(treatments).isVisible(at: now.addingTimeInterval(60)))
        XCTAssertEqual(metric(treatments, at: now.addingTimeInterval(60)).reason, .noTreatments)
    }

    func testHistoricalVisibilityBeforeAndAfterTreatmentDoesNotCountItEarly() throws {
        let treatment = entry(2, minutesAgo: 3 * 24 * 60)
        let window = TherapyModelSettings.visibilityInterval
        func historical(_ offset: TimeInterval, isIOB: Bool = true) -> TherapyMetricState {
            TherapyMetricsManager.localMetric(entries: [treatment], isIOB: isIOB,
                date: treatment.date.addingTimeInterval(offset), settings: settings, currentDate: now)
        }
        XCTAssertEqual(historical(-window).reason, .noTreatments)
        let before = treatment.date.addingTimeInterval(-window + 1)
        XCTAssertEqual(try XCTUnwrap(historical(-window + 1).value(at: before)), 0)
        XCTAssertEqual(try XCTUnwrap(historical(-window + 1, isIOB: false).value(at: before)), 0)
        XCTAssertEqual(try XCTUnwrap(historical(0).value(at: treatment.date)), 2)
        XCTAssertEqual(try XCTUnwrap(historical(window - 1).value(at: treatment.date.addingTimeInterval(window - 1))), 0)
        XCTAssertEqual(historical(window).reason, .noTreatments)
    }

    func testRecentTreatmentKeepsBothLocalMetricsVisibleThroughoutHistory() throws {
        let date = now.addingTimeInterval(-10 * TherapyModelSettings.visibilityInterval)
        for isIOB in [true, false] {
            let state = TherapyMetricsManager.localMetric(entries: [], isIOB: isIOB, date: date,
                settings: settings, currentDate: now, recentEntries: [entry(20, isIOB: false)])
            XCTAssertEqual(try XCTUnwrap(state.value(at: date)), 0)
        }
        let failed = TherapyMetricsManager.localMetric(entries: [], isIOB: true, date: date,
            settings: settings, currentDate: now, recentEntries: nil)
        XCTAssertEqual(failed.reason, .readFailed)
    }

    func testLocalValuesHaveNoApproximationSymbol() {
        XCTAssertEqual(metric([entry(2)]).formatted(isIOB: true, at: now), "2 U")
        XCTAssertEqual(metric([entry(20, isIOB: false)], isIOB: false).formatted(isIOB: false, at: now), "20 g")
        XCTAssertEqual(metric([entry(2, minutesAgo: settings.insulinDuration + 1)]).formatted(isIOB: true, at: now), "0 U")
    }

    func testNoHistoryAndReadFailureAreDifferent() {
        XCTAssertEqual(metric([]).reason, .noTreatments)
        XCTAssertFalse(metric([]).isVisible(at: now))
        XCTAssertEqual(metric(nil).reason, .readFailed)
        XCTAssertNil(metric(nil).value(at: now))
    }

    func testFutureAndInvalidAmountsDoNotEnableVisibility() {
        let treatments = [entry(2, minutesAgo: -1), entry(.nan), entry(.infinity), entry(-2), entry(0)]
        XCTAssertEqual(metric(treatments).reason, .noTreatments)
    }

    func testLocalSnapshotExpiresAt17Minutes() {
        let snapshot = metric([entry(2)])
        XCTAssertNotNil(snapshot.value(at: now.addingTimeInterval(1019)))
        XCTAssertNil(snapshot.value(at: now.addingTimeInterval(1020)))
        XCTAssertTrue(snapshot.isVisible(at: now.addingTimeInterval(1020)))
        XCTAssertNil(snapshot.value(at: now.addingTimeInterval(-61)))
    }

    func testCareLinkIOBAndLocalCOBAreIndependent() throws {
        let external = AIDStatus(condition: .active, style: .careLinkIOB, statusUpdatedAt: now,
            lastActivityAt: now, iob: 1.5, cob: nil, statusTitle: "", staleStatusTitle: "")
        let result = TherapyMetricsManager.resolve(at: now, external: external, policy: policy(therapy: .careLink),
            settings: settings, entries: [entry(10), entry(30, isIOB: false)])
        XCTAssertEqual(result.iob.source, .careLink)
        XCTAssertEqual(try XCTUnwrap(result.iob.value(at: now)), 1.5)
        XCTAssertEqual(result.cob.source, .local)
        XCTAssertEqual(try XCTUnwrap(result.cob.value(at: now)), 30)
    }

    func testExternalOutagesNeverUseLocalFallback() {
        for source in [TherapyDataSourceType.careLink, .nightscout] {
            let result = TherapyMetricsManager.resolve(at: now, external: nil,
                policy: policy(therapy: source, follow: .openAPS), settings: settings,
                entries: [entry(10), entry(30, isIOB: false)])
            XCTAssertNil(result.iob.value(at: now))
            XCTAssertEqual(result.iob.reason, .missingExternalData)
            if source == .nightscout {
                XCTAssertNil(result.cob.value(at: now))
                XCTAssertEqual(result.cob.reason, .missingExternalData)
            }
        }
    }

    func testExternalNegativeAndZeroValuesDoNotRequireTreatments() throws {
        let status = AIDStatus(condition: .active, style: .loop, statusUpdatedAt: now,
            lastActivityAt: now, iob: -0.5, cob: 0, statusTitle: "", staleStatusTitle: "")
        let result = TherapyMetricsManager.resolve(at: now, external: status,
            policy: policy(therapy: .nightscout, follow: .openAPS), settings: settings, entries: [])
        XCTAssertEqual(try XCTUnwrap(result.iob.value(at: now)), -0.5)
        XCTAssertEqual(try XCTUnwrap(result.cob.value(at: now)), 0)
        XCTAssertTrue(result.cob.isVisible(at: now))
        XCTAssertNil(result.iob.value(at: now.addingTimeInterval(1020)))
    }

    func testDefaultSettingsCalculateAutomaticallyAndInvalidCombinationsAreRejected() {
        let defaults = UserDefaults(suiteName: UUID().uuidString)!
        let value = TherapyModelSettings(defaults: defaults)
        XCTAssertNotNil(TherapyMetricsManager.localMetric(entries: [entry(2)], isIOB: true, date: now, settings: value).value(at: now))
        XCTAssertEqual(value.insulinDuration, 600)
        XCTAssertEqual(value.insulinPeak, 75)
        XCTAssertEqual(value.carbDuration, 240)
        var invalid = settings
        invalid.insulinDuration = 180
        invalid.insulinPeak = 90
        XCTAssertFalse(invalid.validInsulin)
        XCTAssertEqual(TherapyMetricsManager.localMetric(entries: [entry(2)], isIOB: true, date: now, settings: invalid).reason, .invalidSettings)
    }

    func testLegacyDisabledPreferencesDoNotSuppressAutomaticMetrics() throws {
        let suite = UUID().uuidString
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suite))
        defer { defaults.removePersistentDomain(forName: suite) }
        defaults.set(false, forKey: "calculateLocalIOB")
        defaults.set(false, forKey: "calculateLocalCOB")
        defaults.set(55.0, forKey: "localInsulinPeak")
        defaults.set(300.0, forKey: "localCarbDuration")
        let savedSettings = TherapyModelSettings(defaults: defaults)
        let entries = [entry(2), entry(20, isIOB: false)]
        let local = TherapyMetricsManager.resolve(at: now, external: nil, policy: policy(), settings: savedSettings, entries: entries)
        XCTAssertEqual(local.iob.value(at: now), 2)
        XCTAssertEqual(local.cob.value(at: now), 20)
        XCTAssertEqual(savedSettings.insulinPeak, 55)
        XCTAssertEqual(savedSettings.carbDuration, 300)

        let external = TherapyMetricsManager.resolve(at: now, external: nil,
            policy: policy(therapy: .nightscout, follow: .openAPS), settings: savedSettings, entries: entries)
        XCTAssertEqual(external.iob.reason, .missingExternalData)
        XCTAssertEqual(external.cob.reason, .missingExternalData)
        XCTAssertNil(external.iob.value(at: now))
        XCTAssertNil(external.cob.value(at: now))
        XCTAssertEqual(TherapyModelSettings(defaults: defaults), savedSettings)
    }

    func testSourceSwitchDoesNotMutateLocalPreferences() {
        let result = TherapyMetricsManager.resolve(at: now, external: nil, policy: policy(), settings: settings, entries: [entry(2)])
        XCTAssertEqual(result.iob.source, .local)
        XCTAssertNotNil(result.iob.value(at: now))
        XCTAssertEqual(settings.insulinPeak, 75)
    }

    func testSharedPayloadRoundTripAndLegacyWatchPayload() throws {
        let snapshot = TherapyMetricsSnapshot(iob: metric([entry(2)]), cob: metric([], isIOB: false))
        XCTAssertEqual(try JSONDecoder().decode(TherapyMetricsSnapshot.self, from: JSONEncoder().encode(snapshot)), snapshot)
        var status = WatchStatus()
        status.therapyMetrics = snapshot
        let data = try JSONEncoder().encode(status)
        var json = try XCTUnwrap(JSONSerialization.jsonObject(with: data) as? [String: Any])
        json.removeValue(forKey: "therapyMetrics")
        let legacy = try JSONDecoder().decode(WatchStatus.self, from: JSONSerialization.data(withJSONObject: json))
        XCTAssertNil(legacy.therapyMetrics)
    }

    @MainActor func testStoredInputSelectionExcludesBasalAndDeletedEntriesAndPreservesDuplicates() async throws {
        let core = CoreDataManager(inMemoryModelName: ConstantsCoreData.modelName)
        let manager = TherapyMetricsManager()
        manager.configure(coreDataManager: core, externalStatus: { nil })
        for type in [TreatmentType.Insulin, .Insulin, .Carbs, .BasalInjection, .Basal, .AutomaticBasal] {
            _ = TreatmentEntry(date: now, value: 2, treatmentType: type, nightscoutEventType: nil, enteredBy: nil, nsManagedObjectContext: core.mainManagedObjectContext)
        }
        let deleted = TreatmentEntry(date: now, value: 99, treatmentType: .Insulin, nightscoutEventType: nil, enteredBy: nil, nsManagedObjectContext: core.mainManagedObjectContext)
        deleted.treatmentdeleted = true
        XCTAssertTrue(core.saveChangesSynchronously())
        let entries = try await readInputs(manager)
        XCTAssertEqual(entries.count, 3)
        XCTAssertEqual(try XCTUnwrap(metric(entries).value(at: now)), 4)
        deleted.treatmentdeleted = false
        XCTAssertTrue(core.saveChangesSynchronously())
        let changed = try await readInputs(manager)
        XCTAssertEqual(changed.count, 4)
        XCTAssertEqual(try XCTUnwrap(metric(changed).value(at: now)), 103)
    }
    func testChartKeepsZeroHistoryAndJumpsAtTreatmentWithoutBridgingHiddenIntervals() {
        let entries = [entry(2, minutesAgo: 60)]
        let start = now.addingTimeInterval(-7200)
        let end = now.addingTimeInterval(86400)
        let result = TherapyMetricsManager.chartSeries(entries: entries, statuses: [], policy: policy(), settings: settings, start: start, end: end)
        XCTAssertFalse(result.cob.isEmpty)
        XCTAssertTrue(result.cob.allSatisfy { $0.amount == 0 })
        XCTAssertEqual(result.iob.first?.date, start)
        XCTAssertEqual(result.iob.first?.amount, 0)
        XCTAssertEqual(result.iob.filter { $0.date == entries[0].date }.map(\.amount), [0, 2])
        XCTAssertEqual(result.iob.last?.amount, 0)
        XCTAssertLessThan(result.iob.last!.date, entries[0].date.addingTimeInterval(86400))
        let second = entry(1)
        let overlapping = TherapyMetricsManager.chartSeries(entries: entries + [second], statuses: [], policy: policy(), settings: settings, start: start, end: end)
        let before = overlapping.iob.last { $0.date < now }
        let after = overlapping.iob.first { $0.date == now }
        XCTAssertEqual(before?.segment, after?.segment)
        let jump = overlapping.iob.filter { $0.date == now }
        XCTAssertEqual(jump.count, 2)
        XCTAssertEqual(jump[1].amount - jump[0].amount, 1, accuracy: 1e-12)
        XCTAssertGreaterThan(jump[0].amount, 0)
        XCTAssertEqual(Set(overlapping.iob.map(\.id)).count, overlapping.iob.count)
    }

    private func status(_ minute: Double, _ iob: Double?, calculatedMinute: Double? = nil) -> NightscoutDeviceStatusSnapshot {
        let date = now.addingTimeInterval(minute * 60)
        return NightscoutDeviceStatusSnapshot(id: "\(minute)", createdAt: date, updatedDate: date, lastCheckedDate: date, lastLoopDate: date, timestamp: calculatedMinute.map { now.addingTimeInterval($0 * 60) }, device: nil, appVersion: nil, activeProfile: nil, iob: iob, cob: nil, eventualBG: nil, currentTarget: nil, isf: nil, insulinReq: nil, bolusVolume: nil, rate: nil, duration: nil, reason: nil, sensitivityRatio: nil, tdd: nil, error: nil, overrideActive: nil, overrideName: nil, overrideMinValue: nil, overrideMaxValue: nil, overrideMultiplier: nil, pumpBatteryPercent: nil, pumpReservoir: nil, pumpIsBolusing: nil, pumpIsSuspended: nil, pumpStatus: nil, pumpStatusTimestamp: nil, pumpManufacturer: nil, pumpModel: nil, uploaderBatteryPercent: nil, uploaderIsCharging: nil)
    }

    func testExternalChartIgnoresIncompleteRowsAndJoinsShortGaps() {
        let records = [status(40, 1), status(5, nil), status(15, 2), status(10, nil), status(5, 0), status(0, -1)]
        let result = TherapyMetricsManager.chartSeries(entries: [entry(99), entry(99, isIOB: false)], statuses: records,
            policy: policy(therapy: .nightscout, follow: .openAPS), settings: settings,
            start: now, end: now.addingTimeInterval(3600))
        XCTAssertEqual(result.iob.map(\.amount), [-1, 0, 2, 1, 1])
        XCTAssertEqual(result.iob[0].segment, result.iob[2].segment)
        XCTAssertEqual(result.iob[2].segment, result.iob[3].segment)
        XCTAssertLessThan(result.iob.last!.date, now.addingTimeInterval(57 * 60))
        XCTAssertEqual(Set(result.iob.map(\.id)).count, result.iob.count)
        XCTAssertTrue(result.cob.isEmpty)

        let clippedStart = now.addingTimeInterval(2.5 * 60)
        let clipped = TherapyMetricsManager.externalChartPoints(statuses: records, isIOB: true,
            start: clippedStart, end: now.addingTimeInterval(20 * 60))
        XCTAssertEqual(clipped.first?.date, clippedStart)
        XCTAssertEqual(clipped.first?.amount, -0.5)
        XCTAssertEqual(clipped.last?.date, now.addingTimeInterval(20 * 60))
        XCTAssertEqual(clipped.last?.amount, 2)

        let expired = TherapyMetricsManager.externalChartPoints(statuses: [status(0, 2)], isIOB: true,
            start: now.addingTimeInterval(17 * 60), end: now.addingTimeInterval(20 * 60))
        XCTAssertTrue(expired.isEmpty)
        let careLink = TherapyMetricsManager.chartSeries(entries: [entry(99), entry(30, isIOB: false)], statuses: [status(0, 2)],
            policy: policy(therapy: .careLink), settings: settings, start: now, end: now.addingTimeInterval(5 * 60))
        XCTAssertTrue(careLink.iob.allSatisfy { $0.amount == 2 })
        XCTAssertEqual(careLink.cob.last?.amount, 30)
        let repeatedCycles = [status(0, 2, calculatedMinute: 0), status(2, 2, calculatedMinute: 0),
            status(5, 1.8, calculatedMinute: 5), status(7, 1.8, calculatedMinute: 5),
            status(10, 1.9, calculatedMinute: 10)]
        let cycles = TherapyMetricsManager.externalChartPoints(statuses: repeatedCycles, isIOB: true,
            start: now, end: now.addingTimeInterval(10 * 60))
        XCTAssertEqual(cycles.map { $0.date.timeIntervalSince(now) / 60 }, [0, 5, 10])
        // Preserve a real increase in net AID IOB, even without a bolus treatment.
        XCTAssertEqual(cycles.map(\.amount), [2, 1.8, 1.9])
        let staleRepeat = TherapyMetricsManager.externalChartPoints(statuses: [status(20, 2, calculatedMinute: 0)],
            isIOB: true, start: now.addingTimeInterval(18 * 60), end: now.addingTimeInterval(25 * 60))
        XCTAssertTrue(staleRepeat.isEmpty)
    }

    func testCombinedPlotPreferenceDefaultsOnAndPreservesExplicitOff() throws {
        let suite = "TherapyToggle-" + UUID().uuidString
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suite))
        defer { defaults.removePersistentDomain(forName: suite) }
        XCTAssertTrue(defaults.showIOBCOB)
        defaults.showIOBCOB = false
        XCTAssertFalse(defaults.showIOBCOB)
        defaults.showIOBCOB = true
        XCTAssertTrue(defaults.showIOBCOB)
    }

    func testStatusHistoryCacheOnlyFetchesMissingEdgesAndResetsBySourceOrRevision() {
        var cache = TherapyStatusHistoryCache()
        let records = [0.0, 5, 10, 15, 20, 25, 30].map { status($0, $0) }
        var requests: [(Double, Double)] = []
        func load(_ from: Double, _ to: Double, key: String = "trio-1") -> [NightscoutDeviceStatusSnapshot] {
            cache.load(key: key, from: now.addingTimeInterval(from * 60), to: now.addingTimeInterval(to * 60)) { start, end in
                requests.append((start.timeIntervalSince(now) / 60, end.timeIntervalSince(now) / 60))
                return records.filter { $0.createdAt >= start && $0.createdAt <= end }
            }
        }
        XCTAssertEqual(load(10, 20).count, 3)
        XCTAssertEqual(load(12, 18).count, 1)
        XCTAssertEqual(requests.count, 1)
        let expanded = load(5, 25)
        XCTAssertEqual(requests.map { $0.0 }, [10, 5, 20])
        XCTAssertEqual(requests.map { $0.1 }, [20, 10, 25])
        XCTAssertEqual(expanded.count, 5)
        XCTAssertEqual(Set(expanded.map(\.id)).count, 5)
        _ = load(5, 25, key: "carelink-1")
        XCTAssertEqual(requests.count, 4)
        _ = load(5, 25, key: "carelink-2")
        XCTAssertEqual(requests.count, 5)
        XCTAssertTrue(load(100, 110, key: "carelink-2").isEmpty)
        XCTAssertEqual(requests.count, 6)
    }

    func testBufferedTherapyClippingInterpolatesEdgesWithoutBridgingGaps() {
        let points = [TherapyChartPoint(date: now, amount: 4, segment: 0),
            TherapyChartPoint(date: now.addingTimeInterval(600), amount: 2, segment: 0),
            TherapyChartPoint(date: now.addingTimeInterval(1800), amount: 1, segment: 1)]
        let series = TherapyChartSeries(iob: points)
        let clipped = series.clipped(from: now.addingTimeInterval(300), to: now.addingTimeInterval(450))
        XCTAssertEqual(clipped.iob.map(\.amount), [3, 2.5])
        XCTAssertTrue(series.clipped(from: now.addingTimeInterval(900), to: now.addingTimeInterval(1200)).iob.isEmpty)
    }

    func testTreatmentSettingsDisableOnlyExternallyOwnedOptions() throws {
        for source in [policy(), policy(therapy: .careLink), policy(therapy: .nightscout, follow: .openAPS)] {
            for (group, external) in [(TreatmentSettingsViewModel.Group.insulin, source.externalIOBSource), (.carbs, source.externalCOBSource)] {
                let model = TreatmentSettingsViewModel(group: group, policyProvider: { source })
                let row = try XCTUnwrap(model.settingsRows(sectionID: 0).first)
                XCTAssertNil(model.sectionTitle())
                XCTAssertEqual(row.isEnabled, external == nil)
                if external != nil {
                    XCTAssertEqual(row.detail, TherapyTexts.text("automatic"))
                    XCTAssertNil(row.control)
                    XCTAssertNil(model.sectionFooter())
                } else {
                    XCTAssertNotNil(row.control)
                    XCTAssertNotNil(model.sectionFooter())
                }
            }
        }
    }

    func testNamedInsulinAndSimpleCarbSettingsResolveLegacyPreferences() throws {
        let suite = "TherapyPresetTests-" + UUID().uuidString
        let defaults = try XCTUnwrap(UserDefaults(suiteName: suite))
        defer { defaults.removePersistentDomain(forName: suite) }
        for preset in TherapyInsulinPreset.allCases {
            defaults.set(preset.peak, forKey: "localInsulinPeak")
            defaults.set(420, forKey: "localInsulinDuration")
            let model = TherapyModelSettings(defaults: defaults)
            XCTAssertEqual(model.insulinPeak, preset.peak)
            XCTAssertEqual(model.insulinDuration, 600)
            XCTAssertTrue(model.validInsulin)
        }
        XCTAssertEqual(TherapyModelSettings.carbDurationChoices, [120, 180, 240, 300, 360, 420, 480])
        for minutes in TherapyModelSettings.carbDurationChoices {
            defaults.set(minutes, forKey: "localCarbDuration")
            let model = TherapyModelSettings(defaults: defaults)
            XCTAssertEqual(model.carbDuration, minutes)
            XCTAssertTrue(model.validCarbs)
        }
        defaults.set(90, forKey: "localCarbDuration")
        XCTAssertEqual(TherapyModelSettings(defaults: defaults).carbDuration, 120)
        defaults.set(290, forKey: "localCarbDuration")
        XCTAssertEqual(TherapyModelSettings(defaults: defaults).carbDuration, 300)
    }

    func testSharedGridDatesRemainClockAnchoredAcrossScrollAndChartRanges() {
        for hours in [3.0, 6, 12, 24] {
            let end = now.addingTimeInterval(123)
            let start = end.addingTimeInterval(-hours * 3600)
            let interval = hours >= 24 ? 4 : hours >= 8 ? 2 : 1
            let dates = ConstantsGlucoseChartSwiftUI.xAxisDates(from: start, to: end, everyHours: interval)
            XCTAssertFalse(dates.isEmpty)
            XCTAssertTrue(dates.allSatisfy { Calendar.current.component(.minute, from: $0) == 0 && Calendar.current.component(.hour, from: $0) % interval == 0 })
            let shifted = ConstantsGlucoseChartSwiftUI.xAxisDates(from: start.addingTimeInterval(1), to: end.addingTimeInterval(1), everyHours: interval)
            XCTAssertEqual(dates, shifted)
        }
    }

    func testIntegratedTherapyScalePreservesRatioAndReducesBothCurves() {
        func point(_ amount: Double) -> TherapyChartPoint { TherapyChartPoint(date: now, amount: amount, segment: 0) }
        for hours in [3.0, 6, 12, 24] {
            let baseline = ConstantsGlucoseChartSwiftUI.minimumChartValueWithBottomSpace(hours: hours)
            XCTAssertEqual(baseline, hours >= 24 ? 0 : -10)
            let scale = TherapyChartScale(series: TherapyChartSeries(iob: [point(15)], cob: [point(70)]), baseline: baseline)
            XCTAssertEqual(scale.glucoseValue(amount: 0, isIOB: true), baseline)
            XCTAssertEqual(scale.glucoseValue(amount: 15, isIOB: true), 100, accuracy: 1e-10)
            XCTAssertLessThan(scale.glucoseValue(amount: 70, isIOB: false), 100)
            XCTAssertLessThan(scale.glucoseValue(amount: -2, isIOB: true), baseline)
            for units in [1.0, 2, 4] {
                XCTAssertEqual(scale.glucoseValue(amount: units, isIOB: true), scale.glucoseValue(amount: units * 7, isIOB: false), accuracy: 1e-10)
            }
            for series in [TherapyChartSeries(iob: [point(30)], cob: [point(70)]), TherapyChartSeries(iob: [point(15)], cob: [point(140)])] {
                let reduced = TherapyChartScale(series: series, baseline: baseline)
                XCTAssertEqual(reduced.reduction, 2)
                XCTAssertEqual(reduced.glucoseValue(amount: 2, isIOB: true), reduced.glucoseValue(amount: 14, isIOB: false), accuracy: 1e-10)
                XCTAssertLessThanOrEqual(reduced.glucoseValue(amount: series.iob[0].amount, isIOB: true), 100)
                XCTAssertLessThanOrEqual(reduced.glucoseValue(amount: series.cob[0].amount, isIOB: false), 100)
            }
        }
    }

    @MainActor func testRenderTherapyInsideGlucoseChartWithAndWithoutBasal() throws {
        let start = now.addingTimeInterval(-3600)
        let end = now.addingTimeInterval(4 * 3600)
        let series = TherapyMetricsManager.chartSeries(entries: [entry(4), entry(30, isIOB: false)], statuses: [], policy: policy(), settings: settings, start: start, end: end)
        for width in [320.0, 768.0] {
            for withBasal in [false, true] {
                var state = GlucoseChartState.empty(startDate: start, endDate: end)
                state.bgReadingDates = stride(from: start.timeIntervalSince1970, through: end.timeIntervalSince1970, by: 300).map { Date(timeIntervalSince1970: $0) }
                state.bgReadingValues = state.bgReadingDates.enumerated().map { 110 + 20 * sin(Double($0.offset) / 8) }
                if withBasal {
                    state.minimumChartValueInMgDl = ConstantsGlucoseChartSwiftUI.minimumChartValueWithBottomSpace(hours: 5)
                    state.treatmentPoints.basalRates = [GlucoseChartPoint(date: start, value: 10, idPrefix: "basal"), GlucoseChartPoint(date: end, value: 10, idPrefix: "basal")]
                    state.treatmentPoints.basalRateFill = state.treatmentPoints.basalRates
                }
                let content = GlucoseChartView(glucoseChartType: .widgetSystemLarge, bgReadingValues: nil, bgReadingDates: nil,
                    isMgDl: true, urgentLowLimitInMgDl: 55, lowLimitInMgDl: 70, highLimitInMgDl: 180, urgentHighLimitInMgDl: 230,
                    liveActivityType: nil, hoursToShowScalingHours: 5, glucoseCircleDiameterScalingHours: 5,
                    showsTreatments: withBasal, overrideChartHeight: 300, overrideChartWidth: width,
                    highContrast: nil, chartState: state)
                    .mainChartYAxisContext().therapyPlots(series)
                    .frame(width: width, height: 300).background(Color.black).environment(\.colorScheme, .dark)
                let renderer = ImageRenderer(content: content)
                renderer.scale = 2
                let attachment = XCTAttachment(image: try XCTUnwrap(renderer.uiImage))
                attachment.name = "Integrated therapy \(Int(width))pt basal=\(withBasal)"
                attachment.lifetime = .keepAlways
                add(attachment)
            }
        }
    }

    @MainActor func testImportedSourceSelectionAndLocallyNamedUploadRoundTrip() async throws {
        let core = CoreDataManager(inMemoryModelName: ConstantsCoreData.modelName)
        let manager = TherapyMetricsManager()
        manager.configure(coreDataManager: core, externalStatus: { nil })
        _ = TreatmentEntry(id: "manual-uploaded", date: now, value: 2, treatmentType: .Insulin, uploaded: true, nightscoutEventType: nil, enteredBy: "My name", nsManagedObjectContext: core.mainManagedObjectContext)
        _ = TreatmentEntry(id: "manual-carelink-name", date: now, value: 1, treatmentType: .Insulin, uploaded: true, nightscoutEventType: nil, enteredBy: "CareLink", nsManagedObjectContext: core.mainManagedObjectContext)
        _ = TreatmentEntry(id: "nightscout", date: now, value: 3, treatmentType: .Insulin, uploaded: true, nightscoutEventType: "Bolus", enteredBy: nil, nsManagedObjectContext: core.mainManagedObjectContext)
        let careLink = TreatmentEntry(id: "carelink", date: now, value: 30, treatmentType: .Carbs, uploaded: true, nightscoutEventType: "Meal Bolus", enteredBy: "CareLink", nsManagedObjectContext: core.mainManagedObjectContext)
        careLink.careLinkSourceIdentifier = "meal-1"
        XCTAssertTrue(core.saveChangesSynchronously())
        let local = try await readInputs(manager, source: .none)
        let nightscout = try await readInputs(manager, source: .nightscout)
        let careLinkInputs = try await readInputs(manager, source: .careLink)
        XCTAssertEqual(local.map(\.amount).sorted(), [1, 2])
        XCTAssertEqual(nightscout.map(\.amount).sorted(), [1, 2, 3])
        XCTAssertEqual(careLinkInputs.map(\.amount).sorted(), [1, 2, 30])
    }

    @MainActor func testPendingWriterChangesAreNotPublishedBeforeStoreSave() async throws {
        let core = CoreDataManager(inMemoryModelName: ConstantsCoreData.modelName)
        let manager = TherapyMetricsManager()
        manager.configure(coreDataManager: core, externalStatus: { nil })
        _ = TreatmentEntry(date: now, value: 2, treatmentType: .Insulin, nightscoutEventType: nil, enteredBy: nil, nsManagedObjectContext: core.mainManagedObjectContext)
        // Saving the child pushes to the writer, but does not commit to the persistent store.
        try core.mainManagedObjectContext.save()
        let pending = try await readInputs(manager)
        XCTAssertTrue(pending.isEmpty)
        XCTAssertTrue(core.saveChangesSynchronously())
        let committed = try await readInputs(manager)
        XCTAssertEqual(committed.count, 1)
    }

    private func readInputs(_ manager: TherapyMetricsManager, source: TherapyDataSourceType = .none) async throws -> [TherapyTreatment] {
        let start = now.addingTimeInterval(-86400), end = now
        let policy = policy(therapy: source), settings = settings
        let result = await Task.detached {
            manager.treatments(from: start, to: end, policy: policy, settings: settings)
        }.value
        return try XCTUnwrap(result)
    }

    @MainActor func testMainThreadColdReadReturnsImmediatelyThenPublishesCachedInputs() async throws {
        let core = CoreDataManager(inMemoryModelName: ConstantsCoreData.modelName)
        let manager = TherapyMetricsManager()
        manager.configure(coreDataManager: core, externalStatus: { nil })
        _ = TreatmentEntry(date: now, value: 2, treatmentType: .Insulin, nightscoutEventType: nil, enteredBy: nil, nsManagedObjectContext: core.mainManagedObjectContext)
        XCTAssertTrue(core.saveChangesSynchronously())
        XCTAssertNil(manager.treatments(from: now.addingTimeInterval(-86400), to: now, policy: policy(), settings: settings))
        var loaded: [TherapyTreatment]?
        for _ in 0..<100 {
            try await Task.sleep(nanoseconds: 20_000_000)
            loaded = manager.treatments(from: now.addingTimeInterval(-86400), to: now, policy: policy(), settings: settings)
            if loaded != nil { break }
        }
        XCTAssertEqual(loaded?.count, 1)
        manager.invalidate(treatmentsChanged: false)
        let cached = manager.treatments(from: now.addingTimeInterval(-86400), to: now, policy: policy(), settings: settings)
        XCTAssertEqual(cached?.count, 1, "Status-only saves must retain treatment inputs")
        manager.invalidate()
        XCTAssertNil(manager.treatments(from: now.addingTimeInterval(-86400), to: now, policy: policy(), settings: settings))
    }

    func testExternalChartJoinBoundaryAndClippingBeyondFreshness() throws {
        for minutes in [31.999, 32, 33] {
            let points = TherapyMetricsManager.externalChartPoints(statuses: [status(0, -1), status(minutes, 3)],
                isIOB: true, start: now, end: now.addingTimeInterval(minutes * 60))
            XCTAssertEqual(points.first?.segment == points.last?.segment, minutes < 32)
        }
        let clipped = TherapyMetricsManager.externalChartPoints(statuses: [status(0, 1), status(30, 4)],
            isIOB: true, start: now.addingTimeInterval(20 * 60), end: now.addingTimeInterval(30 * 60))
        XCTAssertEqual(try XCTUnwrap(clipped.first?.amount), 3, accuracy: 1e-9)
        XCTAssertEqual(clipped.first?.date, now.addingTimeInterval(20 * 60))
        // No later point: retain the existing freshness expiry, without projecting 32 minutes.
        let isolated = TherapyMetricsManager.externalChartPoints(statuses: [status(0, 1)],
            isIOB: true, start: now.addingTimeInterval(20 * 60), end: now.addingTimeInterval(30 * 60))
        XCTAssertTrue(isolated.isEmpty)
    }

    func testChartCancellationStopsLocalAndExternalSampling() {
        let cancellation = TherapyChartCancellation()
        cancellation.cancel()
        let local = TherapyMetricsManager.chartSeries(entries: [entry(2)], statuses: [], policy: policy(), settings: settings,
            start: now, end: now.addingTimeInterval(86400), isCancelled: { cancellation.isCancelled })
        XCTAssertTrue(local.iob.isEmpty && local.cob.isEmpty)
        let external = TherapyMetricsManager.externalChartPoints(statuses: [status(0, 1), status(5, 2)],
            isIOB: true, start: now, end: now.addingTimeInterval(600), isCancelled: { cancellation.isCancelled })
        XCTAssertTrue(external.isEmpty)
    }

    func testInvalidAmountsCannotBreakCompanionEncoding() throws {
        let huge = Double.greatestFiniteMagnitude
        let local = metric([entry(huge), entry(huge)])
        XCTAssertNil(local.amount)
        XCTAssertEqual(local.reason, .invalidSettings)
        XCTAssertNoThrow(try JSONEncoder().encode(local))
        let status = AIDStatus(condition: .active, style: .loop, statusUpdatedAt: now,
            lastActivityAt: now, iob: .infinity, cob: .nan, statusTitle: "Looping", staleStatusTitle: "No data")
        let external = TherapyMetricsSnapshot.external(status, at: now)
        XCTAssertNil(external.iob.amount)
        XCTAssertNil(external.cob.amount)
        XCTAssertEqual(external.iob.reason, .missingExternalData)
        XCTAssertNoThrow(try JSONEncoder().encode(external))
    }

    func testTreatmentSettingsIgnoreInvalidRowIndices() {
        let model = TreatmentSettingsViewModel(group: .insulin)
        for index in [-1, 1, Int.max] {
            XCTAssertEqual(model.settingsRowText(index: index), "")
            XCTAssertNil(model.detailedText(index: index))
            XCTAssertFalse(model.isEnabled(index: index))
        }
    }

    func testTherapyLocalizationsHaveMatchingKeysAndFormatArguments() throws {
        let languages = ["ar", "da", "de", "el", "en", "es", "fi", "fr", "it", "nl", "pl-PL", "pt", "ru", "sl", "sv", "tr", "uk", "zh"]
        func strings(_ language: String, table: String) throws -> [String: String] {
            let url = try XCTUnwrap(Bundle.main.url(forResource: table, withExtension: "strings", subdirectory: nil, localization: language))
            XCTAssertEqual(url.deletingLastPathComponent().lastPathComponent, language + ".lproj")
            let values = try XCTUnwrap(PropertyListSerialization.propertyList(from: Data(contentsOf: url), format: nil) as? [String: String])
            return values.filter { $0.key.hasPrefix("therapy.") }
        }
        for table in ["SettingsViews", "Common"] {
            let english = try strings("en", table: table)
            XCTAssertFalse(english.isEmpty)
            for language in languages {
                let translated = try strings(language, table: table)
                XCTAssertEqual(Set(translated.keys), Set(english.keys), "\(language) \(table)")
                for (key, value) in translated {
                    XCTAssertFalse(value.isEmpty, "\(language) \(key)")
                    XCTAssertEqual(value.components(separatedBy: "%@").count,
                                   english[key]?.components(separatedBy: "%@").count, "\(language) \(key)")
                }
            }
        }
    }

    func testCollapsedChartRangesAndUnrepresentableJumpsHaveNoDuplicateIDs() {
        let series = TherapyChartSeries(iob: [TherapyChartPoint(date: now.addingTimeInterval(-60), amount: 2, segment: 0),
                                             TherapyChartPoint(date: now.addingTimeInterval(60), amount: 1, segment: 0)])
        XCTAssertTrue(series.clipped(from: now, to: now).iob.isEmpty)
        let points = TherapyMetricsManager.chartSeries(entries: [entry(2, minutesAgo: 10), entry(Double.leastNonzeroMagnitude)],
            statuses: [], policy: policy(), settings: settings, start: now.addingTimeInterval(-600), end: now).iob
        XCTAssertEqual(Set(points.map(\.id)).count, points.count)
    }

}
